spring.application.name=secure-app
server.port=8081

aws.accessKeyId=${AWS_ACCESS_KEY_ID}
aws.secretAccessKey=${AWS_SECRET_ACCESS_KEY}
aws.region=${AWS_REGION}
aws.s3.endpoint=${AWS_ENDPOINT}

bucket.name=${BUCKET_NAME}

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.access=unrestricted
